version: '2'
services:
  jenkins:
    image: 'bitnami/jenkins:2'
    environment:
      JENKINS_USERNAME: edonadei
      JENKINS_PASSWORD: password
      JENKINS_HOME: /opt/edonadei/jenkins/jenkins_home
    ports:
      - '80:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - 'jenkins_data:/edonadei'
volumes:
  jenkins_data:
    driver: local