version: '2'

services:
    kafka-zookeeper:
        image: spotify/kafka
        ports:
        - "2181:2181"
        - "9092:9092"
        environment:
        - KAFKA_ADVERTISED_HOST=localhost
        - KAFKA_ADVERTISED_PORT=9092
        - KAFKA_DELETE_TOPIC_ENABLE=true
        - KAFKA_LOG_RETENTION_HOURS=1
        - KAFKA_MESSAGE_MAX_BYTES=10000000
        - KAFKA_REPLICA_FETCH_MAX_BYTES=10000000
        - KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS=60000
        - KAFKA_NUM_PARTITIONS=3
        - KAFKA_DELETE_RETENTION_MS=1000
    
    kafka-manager:
        image: sheepkiller/kafka-manager:latest
        ports:
            - "9000:9000"
        links:
            - kafka-zookeeper
        environment:
            ZK_HOSTS: kafka-zookeeper:2181
            APPLICATION_SECRET: letmein
            KM_ARGS: -Djava.net.preferIPv4Stack=true

    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_BASICAUTH_USERNAME: edonadei
            ME_CONFIG_BASICAUTH_PASSWORD: password
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
        links:
            - mongo
        networks:
            - mongo-compose-network

    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - "27017:27017"
        networks:
            - mongo-compose-network

    jenkins:
        image: 'bitnami/jenkins:2'
        environment:
            JENKINS_USERNAME: edonadei
            JENKINS_PASSWORD: password
            JENKINS_HOME: /opt/edonadei/jenkins_data/jenkins/jenkins_home
        ports:
            - '80:8080'
            - '443:8443'
            - '50000:50000'

networks: 
    mongo-compose-network:
        driver: bridge

